# Generated by Django 3.2.22 on 2023-11-01 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_auto_20231101_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00am'), (datetime.time(9, 15), '9:15am'), (datetime.time(9, 30), '9:30am'), (datetime.time(9, 45), '9:45am')]),
        ),
    ]
