# Generated by Django 3.2.22 on 2023-11-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0004_booking_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date_of_booking', 'start_time', 'end_time']},
        ),
    ]
