# Generated by Django 3.2.22 on 2023-11-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0009_auto_20231116_1634'),
        ('booking_system', '0009_auto_20231116_1730'),
    ]

    operations = [
    ]
