# Generated by Django 3.2.22 on 2023-11-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0011_alter_booking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
